/*
 * Decompiled with CFR 0.150.
 */
package tools.use.xml.cleaner;

import client.inventory.MapleRing;
import java.util.ArrayList;
import java.util.List;

public class ItemData {
    public static /* synthetic */ String[] keepString;
    public static final /* synthetic */ List<String> Data;

    public static /* synthetic */ {
        Data = new ArrayList<String>();
        String[] arrstring = new String[21];
        arrstring[0] = MapleRing.ALLATORIxDEMO("\u007f");
        arrstring[1] = MapleRing.ALLATORIxDEMO("=v9h(");
        arrstring[2] = MapleRing.ALLATORIxDEMO("?");
        arrstring[3] = MapleRing.ALLATORIxDEMO("\u007f*u0");
        arrstring[4] = MapleRing.ALLATORIxDEMO("\u001aH\u0015");
        arrstring[5] = MapleRing.ALLATORIxDEMO("\u0014U\u0010");
        arrstring[6] = MapleRing.ALLATORIxDEMO("s(\u007f1");
        arrstring[7] = MapleRing.ALLATORIxDEMO("1{;s?");
        arrstring[8] = MapleRing.ALLATORIxDEMO("\u0011U\u0012");
        arrstring[9] = MapleRing.ALLATORIxDEMO("\u000f[\b");
        arrstring[10] = MapleRing.ALLATORIxDEMO("\u000fO\u0012");
        arrstring[11] = MapleRing.ALLATORIxDEMO("/n=t8");
        arrstring[12] = MapleRing.ALLATORIxDEMO("i({>");
        arrstring[13] = MapleRing.ALLATORIxDEMO("/m5t;");
        arrstring[14] = MapleRing.ALLATORIxDEMO("\bR\t");
        arrstring[15] = MapleRing.ALLATORIxDEMO("\bO\u0019");
        arrstring[16] = MapleRing.ALLATORIxDEMO("\u000b_\u0018");
        arrstring[17] = "bobo";
        arrstring[18] = MapleRing.ALLATORIxDEMO("\u0003r=i4");
        arrstring[19] = MapleRing.ALLATORIxDEMO("4r");
        arrstring[20] = "/";
        keepString = arrstring;
        ItemData.ALLATORIxDEMO();
    }

    private static /* synthetic */ void ALLATORIxDEMO() {
        Data.add(MapleRing.ALLATORIxDEMO("{l"));
        Data.add(MapleRing.ALLATORIxDEMO("{m"));
        Data.add(MapleRing.ALLATORIxDEMO("=y?"));
        Data.add(MapleRing.ALLATORIxDEMO("=y?H=n9"));
        Data.add(MapleRing.ALLATORIxDEMO("=y("));
        Data.add(MapleRing.ALLATORIxDEMO("{?n5u2"));
        Data.add(MapleRing.ALLATORIxDEMO("=~8"));
        Data.add(MapleRing.ALLATORIxDEMO("{8~\u0018{%"));
        Data.add(MapleRing.ALLATORIxDEMO("=~8N5w9"));
        Data.add(MapleRing.ALLATORIxDEMO("=s.i(h5q9"));
        Data.add(MapleRing.ALLATORIxDEMO("=v9h("));
        Data.add(MapleRing.ALLATORIxDEMO("{0\u007f.nn"));
        Data.add(MapleRing.ALLATORIxDEMO("{0\u007f.no"));
        Data.add(MapleRing.ALLATORIxDEMO("{0\u007f.nh"));
        Data.add(MapleRing.ALLATORIxDEMO("{0\u007f.ni"));
        Data.add(MapleRing.ALLATORIxDEMO("{0\u007f.nj"));
        Data.add(MapleRing.ALLATORIxDEMO("=v5}2"));
        Data.add(MapleRing.ALLATORIxDEMO("=v,r="));
        Data.add(MapleRing.ALLATORIxDEMO("=t;h%"));
        Data.add(MapleRing.ALLATORIxDEMO("=t;h%E/r3h("));
        Data.add(MapleRing.ALLATORIxDEMO("=h.u;{2y9"));
        Data.add(MapleRing.ALLATORIxDEMO("=i/{/i5t=n5u2"));
        Data.add(MapleRing.ALLATORIxDEMO("{/i=i/s2{(s3t\u000f"));
        Data.add(MapleRing.ALLATORIxDEMO("=i/{)v(\u007f."));
        Data.add(MapleRing.ALLATORIxDEMO("=o(u\u000e\u007f=y("));
        Data.add(MapleRing.ALLATORIxDEMO("{)n3I,\u007f=q5t;"));
        Data.add(MapleRing.ALLATORIxDEMO("=l9t;\u007f."));
        Data.add(MapleRing.ALLATORIxDEMO("x=y7}.t8"));
        Data.add(MapleRing.ALLATORIxDEMO("x=y7i,s2"));
        Data.add(MapleRing.ALLATORIxDEMO("x=y7i(\u007f,"));
        Data.add(MapleRing.ALLATORIxDEMO("x=w>u3"));
        Data.add(MapleRing.ALLATORIxDEMO(">{.h5\u007f."));
        Data.add(MapleRing.ALLATORIxDEMO(">\u007f0y4"));
        Data.add(MapleRing.ALLATORIxDEMO(">\u007f.i9h7"));
        Data.add(MapleRing.ALLATORIxDEMO("x9m5v8\u007f.\u007f8"));
        Data.add(MapleRing.ALLATORIxDEMO("\u001e\\\u000fq5v0"));
        Data.add(MapleRing.ALLATORIxDEMO(">}1J=n4"));
        Data.add(MapleRing.ALLATORIxDEMO(">s;I5`9"));
        Data.add(MapleRing.ALLATORIxDEMO(">s.~9c9"));
        Data.add(MapleRing.ALLATORIxDEMO("x0{?q\tj;h=~9"));
        Data.add(MapleRing.ALLATORIxDEMO(">v=~9"));
        Data.add(MapleRing.ALLATORIxDEMO("x0s&`=h8"));
        Data.add(MapleRing.ALLATORIxDEMO(">v)i4"));
        Data.add(MapleRing.ALLATORIxDEMO("x3u7"));
        Data.add(MapleRing.ALLATORIxDEMO(">u3i(\u007f."));
        Data.add(MapleRing.ALLATORIxDEMO("x3n(u1"));
        Data.add(MapleRing.ALLATORIxDEMO(">h=t8s/rm"));
        Data.add(MapleRing.ALLATORIxDEMO(">h=t8s/rn"));
        Data.add(MapleRing.ALLATORIxDEMO(">h5~0\u007f\u0011i;N%j9"));
        Data.add(MapleRing.ALLATORIxDEMO("x.s8v9J.u,"));
        Data.add(MapleRing.ALLATORIxDEMO(">h5~0\u007f\fh3j\u001fr;"));
        Data.add(MapleRing.ALLATORIxDEMO(">o:|\u001dv0"));
        Data.add(MapleRing.ALLATORIxDEMO("x)v0\u007f("));
        Data.add(MapleRing.ALLATORIxDEMO("x)h/n9hm"));
        Data.add(MapleRing.ALLATORIxDEMO("x)h/n9hn"));
        Data.add(MapleRing.ALLATORIxDEMO("?"));
        Data.add(MapleRing.ALLATORIxDEMO("\u001f"));
        Data.add(MapleRing.ALLATORIxDEMO("ym"));
        Data.add(MapleRing.ALLATORIxDEMO("?+l"));
        Data.add(MapleRing.ALLATORIxDEMO("ym*\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("ym*\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("ym*\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("ym*\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("ym*\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("ym*\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("ym*\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("ym*\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("?+m"));
        Data.add(MapleRing.ALLATORIxDEMO("ym+\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("ym+\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("ym+\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("ym+\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("ym+\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("ym+\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("ym+\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("ym+\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("?+n"));
        Data.add(MapleRing.ALLATORIxDEMO("ym(\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("ym(\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("ym(\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("ym(\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("ym(\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("ym(\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("ym(\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("ym(\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("?+o"));
        Data.add(MapleRing.ALLATORIxDEMO("ym)\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("ym)\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("ym)\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("ym)\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("ym)\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("ym)\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("ym)\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("ym)\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("?+h"));
        Data.add(MapleRing.ALLATORIxDEMO("ym.\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("ym.\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("ym.\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("ym.\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("ym.\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("ym.\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("ym.\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("ym.\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("?+i"));
        Data.add(MapleRing.ALLATORIxDEMO("ym/\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("ym/\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("ym/\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("ym/\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("ym/\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("ym/\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("ym/\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("ym/\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("?+j"));
        Data.add(MapleRing.ALLATORIxDEMO("ym,\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("ym,\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("ym,\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("ym,\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("ym,\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("ym,\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("ym,\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("ym,\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("?+k"));
        Data.add(MapleRing.ALLATORIxDEMO("ym-\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("ym-\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("ym-\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("ym-\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("ym-\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("ym-\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("ym-\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("ym-\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("?+d"));
        Data.add(MapleRing.ALLATORIxDEMO("ym\"\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("ym\"\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("ym\"\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("ym\"\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("ym\"\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("ym\"\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("ym\"\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("ym\"\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("?+e"));
        Data.add(MapleRing.ALLATORIxDEMO("ym#\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("ym#\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("ym#\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("ym#\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("ym#\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("ym#\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("ym#\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("ym#\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("?+\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("?+\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("?+\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("?+\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("?+\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("?+\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("?+\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("?+\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("yn"));
        Data.add(MapleRing.ALLATORIxDEMO("?(l"));
        Data.add(MapleRing.ALLATORIxDEMO("yn*\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("yn*\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("yn*\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("yn*\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("yn*\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("yn*\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("yn*\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("yn*\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("?(m"));
        Data.add(MapleRing.ALLATORIxDEMO("yn+\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("yn+\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("yn+\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("yn+\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("yn+\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("yn+\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("yn+\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("yn+\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("?(n"));
        Data.add(MapleRing.ALLATORIxDEMO("yn(\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("yn(\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("yn(\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("yn(\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("yn(\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("yn(\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("yn(\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("yn(\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("?(o"));
        Data.add(MapleRing.ALLATORIxDEMO("yn)\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("yn)\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("yn)\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("yn)\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("yn)\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("yn)\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("yn)\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("yn)\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("?(h"));
        Data.add(MapleRing.ALLATORIxDEMO("yn.\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("yn.\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("yn.\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("yn.\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("yn.\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("yn.\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("yn.\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("yn.\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("?(i"));
        Data.add(MapleRing.ALLATORIxDEMO("yn/\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("yn/\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("yn/\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("yn/\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("yn/\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("yn/\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("yn/\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("yn/\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("?(j"));
        Data.add(MapleRing.ALLATORIxDEMO("yn,\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("yn,\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("yn,\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("yn,\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("yn,\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("yn,\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("yn,\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("yn,\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("?(k"));
        Data.add(MapleRing.ALLATORIxDEMO("yn-\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("yn-\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("yn-\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("yn-\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("yn-\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("yn-\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("yn-\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("yn-\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("?(d"));
        Data.add(MapleRing.ALLATORIxDEMO("yn\"\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("yn\"\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("yn\"\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("yn\"\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("yn\"\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("yn\"\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("yn\"\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("yn\"\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("?(e"));
        Data.add(MapleRing.ALLATORIxDEMO("yn#\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("yn#\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("yn#\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("yn#\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("yn#\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("yn#\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("yn#\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("yn#\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("?(\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("?(\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("?(\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("?(\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("?(\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("?(\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("?(\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("?(\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("yo"));
        Data.add(MapleRing.ALLATORIxDEMO("?)l"));
        Data.add(MapleRing.ALLATORIxDEMO("yo*\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("yo*\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("yo*\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("yo*\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("yo*\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("yo*\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("yo*\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("yo*\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("?)m"));
        Data.add(MapleRing.ALLATORIxDEMO("?)mEo"));
        Data.add(MapleRing.ALLATORIxDEMO("yo+\u0003):"));
        Data.add(MapleRing.ALLATORIxDEMO("yo+\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("yo+\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("yo+\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("yo+\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("yo+\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("yo+\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("yo+\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("yo+\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("?)n"));
        Data.add(MapleRing.ALLATORIxDEMO("?)nEo"));
        Data.add(MapleRing.ALLATORIxDEMO("yo(\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("yo(\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("yo(\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("yo(\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("yo(\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("yo(\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("yo(\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("yo(\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("?)o"));
        Data.add(MapleRing.ALLATORIxDEMO("yo)\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("yo)\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("yo)\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("yo)\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("yo)\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("yo)\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("yo)\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("yo)\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("?)h"));
        Data.add(MapleRing.ALLATORIxDEMO("?)hEo"));
        Data.add(MapleRing.ALLATORIxDEMO("yo.\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("yo.\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("yo.\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("yo.\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("yo.\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("yo.\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("yo.\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("yo.\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("?)i"));
        Data.add(MapleRing.ALLATORIxDEMO("?)iEo"));
        Data.add(MapleRing.ALLATORIxDEMO("yo/\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("yo/\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("yo/\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("yo/\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("yo/\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("yo/\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("yo/\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("yo/\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("?)j"));
        Data.add(MapleRing.ALLATORIxDEMO("yo,\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("yo,\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("yo,\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("yo,\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("yo,\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("yo,\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("yo,\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("yo,\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("?)k"));
        Data.add(MapleRing.ALLATORIxDEMO("yo-\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("yo-\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("yo-\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("yo-\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("yo-\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("yo-\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("yo-\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("yo-\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("?)d"));
        Data.add(MapleRing.ALLATORIxDEMO("yo\"\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("yo\"\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("yo\"\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("yo\"\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("yo\"\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("yo\"\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("yo\"\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("yo\"\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("?)\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("?)\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("?)\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("?)\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("?)\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("?)\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("?)\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("?)\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("yh"));
        Data.add(MapleRing.ALLATORIxDEMO("?.\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("?.\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("?.\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("?.\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("?.\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("?.\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("?.\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("?.\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("yi"));
        Data.add(MapleRing.ALLATORIxDEMO("?/\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("?/\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("?/\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("?/\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("?/\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("?/\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("?/\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("?/\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("yj"));
        Data.add(MapleRing.ALLATORIxDEMO("?,\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("?,\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("?,\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("?,\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("?,\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("?,\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("?,\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("?,\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("yk"));
        Data.add(MapleRing.ALLATORIxDEMO("?-\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("?-\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("?-\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("?-\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("?-\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("?-\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("?-\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("?-\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("yd"));
        Data.add(MapleRing.ALLATORIxDEMO("?\"\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("?\"\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("?\"\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("?\"\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("?\"\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("?\"\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("?\"\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("?\"\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("ye"));
        Data.add(MapleRing.ALLATORIxDEMO("?#\u0003|m"));
        Data.add(MapleRing.ALLATORIxDEMO("?#\u0003|n"));
        Data.add(MapleRing.ALLATORIxDEMO("?#\u0003|o"));
        Data.add(MapleRing.ALLATORIxDEMO("?#\u0003|h"));
        Data.add(MapleRing.ALLATORIxDEMO("?#\u0003im"));
        Data.add(MapleRing.ALLATORIxDEMO("?#\u0003in"));
        Data.add(MapleRing.ALLATORIxDEMO("?#\u0003io"));
        Data.add(MapleRing.ALLATORIxDEMO("?#\u0003ih"));
        Data.add(MapleRing.ALLATORIxDEMO("y=t2u2"));
        Data.add(MapleRing.ALLATORIxDEMO("y=i4"));
        Data.add(MapleRing.ALLATORIxDEMO("?{/r\u0019b,N5y7\u007f(U2"));
        Data.add(MapleRing.ALLATORIxDEMO("y4{5t0s;r(t5t;"));
        Data.add(MapleRing.ALLATORIxDEMO("y4{2}9"));
        Data.add(MapleRing.ALLATORIxDEMO("?r=t;\u007fm"));
        Data.add(MapleRing.ALLATORIxDEMO("y4{.}9"));
        Data.add(MapleRing.ALLATORIxDEMO("y4{.w5t;"));
        Data.add(MapleRing.ALLATORIxDEMO("y4{("));
        Data.add(MapleRing.ALLATORIxDEMO("?r=n\u001e{0v3u2"));
        Data.add(MapleRing.ALLATORIxDEMO("?r9y7W5h3X%S(\u007f1"));
        Data.add(MapleRing.ALLATORIxDEMO("y4\u007f9h/"));
        Data.add(MapleRing.ALLATORIxDEMO("?r.s/n1{/"));
        Data.add(MapleRing.ALLATORIxDEMO("?r)"));
        Data.add(MapleRing.ALLATORIxDEMO("?v."));
        Data.add(MapleRing.ALLATORIxDEMO("y3w>{(I(\u007f,"));
        Data.add(MapleRing.ALLATORIxDEMO("?u1w=t8"));
        Data.add(MapleRing.ALLATORIxDEMO("?u1j=i/W=q9"));
        Data.add(MapleRing.ALLATORIxDEMO("y3w,{/i\ti9"));
        Data.add(MapleRing.ALLATORIxDEMO("y3w,v=s2"));
        Data.add(MapleRing.ALLATORIxDEMO("?u2"));
        Data.add(MapleRing.ALLATORIxDEMO("y3t/o1\u007f\u001fu)t("));
        Data.add(MapleRing.ALLATORIxDEMO("?u2i)w9Y3o2n\u0011\u007f/i=}9"));
        Data.add(MapleRing.ALLATORIxDEMO("?u2i)w9R\f"));
        Data.add(MapleRing.ALLATORIxDEMO("?u2i)w9S(\u007f1"));
        Data.add(MapleRing.ALLATORIxDEMO("?u2i)w9W\f"));
        Data.add(MapleRing.ALLATORIxDEMO("?u2i)w9U2J5y7o,"));
        Data.add(MapleRing.ALLATORIxDEMO("?u3v5t;\u007f:|9y("));
        Data.add(MapleRing.ALLATORIxDEMO("?u)t("));
        Data.add(MapleRing.ALLATORIxDEMO("y,"));
        Data.add(MapleRing.ALLATORIxDEMO("y.\u007f=n9"));
        Data.add(MapleRing.ALLATORIxDEMO("?h%"));
        Data.add(MapleRing.ALLATORIxDEMO("?o.i9"));
        Data.add(MapleRing.ALLATORIxDEMO("y)h/\u007f8"));
        Data.add(MapleRing.ALLATORIxDEMO("y)n9"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0018"));
        Data.add(MapleRing.ALLATORIxDEMO("~=w="));
        Data.add(MapleRing.ALLATORIxDEMO("8{2y9"));
        Data.add(MapleRing.ALLATORIxDEMO("~=h7t9i/"));
        Data.add(MapleRing.ALLATORIxDEMO("8{.q/s;r("));
        Data.add(MapleRing.ALLATORIxDEMO("~9{8"));
        Data.add(MapleRing.ALLATORIxDEMO("8\u007f:{)v("));
        Data.add(MapleRing.ALLATORIxDEMO("~9|9t/\u007f\u001dn("));
        Data.add(MapleRing.ALLATORIxDEMO("~9|9t/\u007f\u000fn=n9"));
        Data.add(MapleRing.ALLATORIxDEMO("8\u007f0{%"));
        Data.add(MapleRing.ALLATORIxDEMO("~9v=c\u0011i;"));
        Data.add(MapleRing.ALLATORIxDEMO("8\u007f0n="));
        Data.add(MapleRing.ALLATORIxDEMO("~9w3v5n5u2"));
        Data.add(MapleRing.ALLATORIxDEMO("~9h5~9"));
        Data.add(MapleRing.ALLATORIxDEMO("~9i?"));
        Data.add(MapleRing.ALLATORIxDEMO("8s.\u007f?n5u2"));
        Data.add(MapleRing.ALLATORIxDEMO("~5i=x0\u007f8"));
        Data.add(MapleRing.ALLATORIxDEMO("8s/n=t?\u007f\u0004"));
        Data.add(MapleRing.ALLATORIxDEMO("8s/n=t?\u007f\u0005"));
        Data.add(MapleRing.ALLATORIxDEMO("~3p=t;i4s9v8"));
        Data.add(MapleRing.ALLATORIxDEMO("8u2t3"));
        Data.add(MapleRing.ALLATORIxDEMO("~3o>v9[(n=y7"));
        Data.add(MapleRing.ALLATORIxDEMO("~3o>v9|5h9"));
        Data.add(MapleRing.ALLATORIxDEMO("8u)x0\u007f)j,\u007f."));
        Data.add(MapleRing.ALLATORIxDEMO("~.{;u2i(h5q9"));
        Data.add(MapleRing.ALLATORIxDEMO("8h3j\u001ev3y7"));
        Data.add(MapleRing.ALLATORIxDEMO("8h3j\u000fm9\u007f,"));
        Data.add(MapleRing.ALLATORIxDEMO("~)t;"));
        Data.add(MapleRing.ALLATORIxDEMO("9"));
        Data.add(MapleRing.ALLATORIxDEMO("9{("));
        Data.add(MapleRing.ALLATORIxDEMO("\u007f>o.i(\u007f."));
        Data.add(MapleRing.ALLATORIxDEMO("\u007f8h=s2"));
        Data.add(MapleRing.ALLATORIxDEMO("\u007f:|9y("));
        Data.add(MapleRing.ALLATORIxDEMO("_:|9y("));
        Data.add(MapleRing.ALLATORIxDEMO("9|:\u007f?nn"));
        Data.add(MapleRing.ALLATORIxDEMO("\u007f\u0011{,"));
        Data.add(MapleRing.ALLATORIxDEMO("9w3n5u2"));
        Data.add(MapleRing.ALLATORIxDEMO("\u007f1j0u%\u007f9"));
        Data.add(MapleRing.ALLATORIxDEMO("\u007f3h>"));
        Data.add(MapleRing.ALLATORIxDEMO("9l="));
        Data.add(MapleRing.ALLATORIxDEMO("9l=H=n9"));
        Data.add(MapleRing.ALLATORIxDEMO("\u007f*\u007f2n\fu5t("));
        Data.add(MapleRing.ALLATORIxDEMO("9l9t(H=n9"));
        Data.add(MapleRing.ALLATORIxDEMO("\u007f*u0"));
        Data.add(MapleRing.ALLATORIxDEMO("9l3vm"));
        Data.add(MapleRing.ALLATORIxDEMO("9l3vn"));
        Data.add(MapleRing.ALLATORIxDEMO("9l3vo"));
        Data.add(MapleRing.ALLATORIxDEMO("9l3vh"));
        Data.add(MapleRing.ALLATORIxDEMO("9l3vi"));
        Data.add(MapleRing.ALLATORIxDEMO("\u007f*u0T3"));
        Data.add(MapleRing.ALLATORIxDEMO("9l3v\fh3xm"));
        Data.add(MapleRing.ALLATORIxDEMO("9l3v\fh3xn"));
        Data.add(MapleRing.ALLATORIxDEMO("9l3v\fh3xo"));
        Data.add(MapleRing.ALLATORIxDEMO("9l3v\fh3xh"));
        Data.add(MapleRing.ALLATORIxDEMO("9l3v\fh3xi"));
        Data.add(MapleRing.ALLATORIxDEMO("9l3v\u000e\u007f-S(\u007f1S\u0018"));
        Data.add(MapleRing.ALLATORIxDEMO("9l3v\u000e\u007f-J9n\u0010l0"));
        Data.add(MapleRing.ALLATORIxDEMO("9b,"));
        Data.add(MapleRing.ALLATORIxDEMO("9b,X)|:"));
        Data.add(MapleRing.ALLATORIxDEMO("\u007f$j5t?"));
        Data.add(MapleRing.ALLATORIxDEMO("\u007f$j5h9U2V3}3o("));
        Data.add(MapleRing.ALLATORIxDEMO("9b,H=n9"));
        Data.add(MapleRing.ALLATORIxDEMO("9c9"));
        Data.add(MapleRing.ALLATORIxDEMO("\u001a"));
        Data.add(MapleRing.ALLATORIxDEMO("|mE:"));
        Data.add(MapleRing.ALLATORIxDEMO("|mE/"));
        Data.add(MapleRing.ALLATORIxDEMO("|nE:"));
        Data.add(MapleRing.ALLATORIxDEMO("|nE/"));
        Data.add(MapleRing.ALLATORIxDEMO("|oE:"));
        Data.add(MapleRing.ALLATORIxDEMO("|oE/"));
        Data.add(MapleRing.ALLATORIxDEMO("|hE:"));
        Data.add(MapleRing.ALLATORIxDEMO("|hE/"));
        Data.add(MapleRing.ALLATORIxDEMO("|=s0"));
        Data.add(MapleRing.ALLATORIxDEMO("|=q9"));
        Data.add(MapleRing.ALLATORIxDEMO("|=h("));
        Data.add(MapleRing.ALLATORIxDEMO("|=l3h5n9S(\u007f1"));
        Data.add(MapleRing.ALLATORIxDEMO(":s;r("));
        Data.add(MapleRing.ALLATORIxDEMO("|5h9x)h2\u007f."));
        Data.add(MapleRing.ALLATORIxDEMO("|5h9i(h5q9"));
        Data.add(MapleRing.ALLATORIxDEMO(":s.i(I5}2o/"));
        Data.add(MapleRing.ALLATORIxDEMO("|5i("));
        Data.add(MapleRing.ALLATORIxDEMO(":s$\u007f8"));
        Data.add(MapleRing.ALLATORIxDEMO(":v=w9}9{."));
        Data.add(MapleRing.ALLATORIxDEMO(":v3{("));
        Data.add(MapleRing.ALLATORIxDEMO(":v3{(N%j9"));
        Data.add(MapleRing.ALLATORIxDEMO(":v%"));
        Data.add(MapleRing.ALLATORIxDEMO("|3v0u+"));
        Data.add(MapleRing.ALLATORIxDEMO("\\3t("));
        Data.add(MapleRing.ALLATORIxDEMO("|3u8"));
        Data.add(MapleRing.ALLATORIxDEMO("\u001aH\u0015 l*q*n"));
        Data.add(MapleRing.ALLATORIxDEMO("\u001aH\u0015 l*q*j"));
        Data.add(MapleRing.ALLATORIxDEMO("\u001aH\u0015 l*q(h"));
        Data.add(MapleRing.ALLATORIxDEMO("\u001aH\u0015 l(q*j"));
        Data.add(MapleRing.ALLATORIxDEMO("\u001aH\u0015 l,q+l"));
        Data.add(MapleRing.ALLATORIxDEMO("\u001aH\u0015 l,q+n"));
        Data.add(MapleRing.ALLATORIxDEMO("\u001aH\u0015 m*q+h"));
        Data.add(MapleRing.ALLATORIxDEMO("\u001aH\u0015 m(q+d"));
        Data.add(MapleRing.ALLATORIxDEMO("\u001aH\u0015 m.q+d"));
        Data.add(MapleRing.ALLATORIxDEMO("\u001aH\u0015 m\"q(n"));
        Data.add(MapleRing.ALLATORIxDEMO("\u001aH\u0015 m\"q(h"));
        Data.add(MapleRing.ALLATORIxDEMO("\u001aH\u0015 n(q(h"));
        Data.add(MapleRing.ALLATORIxDEMO(":h3t("));
        Data.add(MapleRing.ALLATORIxDEMO(":o0v\u000fm5t;^3o>v9"));
        Data.add(MapleRing.ALLATORIxDEMO(";\u007f2\u007f/s/"));
        Data.add(MapleRing.ALLATORIxDEMO(";r3i("));
        Data.add(MapleRing.ALLATORIxDEMO(";v5n(\u007f."));
        Data.add(MapleRing.ALLATORIxDEMO("}3"));
        Data.add(MapleRing.ALLATORIxDEMO("}3u8"));
        Data.add(MapleRing.ALLATORIxDEMO(";u3~>u%"));
        Data.add(MapleRing.ALLATORIxDEMO(";h=~9"));
        Data.add(MapleRing.ALLATORIxDEMO("})s({."));
        Data.add(MapleRing.ALLATORIxDEMO("r=t8"));
        Data.add(MapleRing.ALLATORIxDEMO("4{2~;o2"));
        Data.add(MapleRing.ALLATORIxDEMO("4{2~/"));
        Data.add(MapleRing.ALLATORIxDEMO("r=t;"));
        Data.add(MapleRing.ALLATORIxDEMO("4{,j%"));
        Data.add(MapleRing.ALLATORIxDEMO("r9{0"));
        Data.add(MapleRing.ALLATORIxDEMO("4s("));
        Data.add(MapleRing.ALLATORIxDEMO("\u0014U\u0010 l*q*n"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0014U\u0010 l*q*j"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0014U\u0010 l*q(h"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0014U\u0010 l(q*j"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0014U\u0010 l,q+l"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0014U\u0010 l,q+n"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0014U\u0010 m*q+h"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0014U\u0010 m(q+d"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0014U\u0010 m.q+d"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0014U\u0010 m\"q(n"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0014U\u0010 m\"q(h"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0014U\u0010 n(q(h"));
        Data.add(MapleRing.ALLATORIxDEMO("r3v%i4s9v8"));
        Data.add(MapleRing.ALLATORIxDEMO("r3w5t;"));
        Data.add(MapleRing.ALLATORIxDEMO("r,"));
        Data.add(MapleRing.ALLATORIxDEMO("4j\u000e"));
        Data.add(MapleRing.ALLATORIxDEMO("4o;"));
        Data.add(MapleRing.ALLATORIxDEMO("r)t;h%"));
        Data.add(MapleRing.ALLATORIxDEMO("r%x.s8"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0015"));
        Data.add(MapleRing.ALLATORIxDEMO("s?\u007f>u$"));
        Data.add(MapleRing.ALLATORIxDEMO("s?\u007f/n3h1"));
        Data.add(MapleRing.ALLATORIxDEMO("s?u2"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0015y3tl"));
        Data.add(MapleRing.ALLATORIxDEMO("5y3tm"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0015y3tm"));
        Data.add(MapleRing.ALLATORIxDEMO("S?u2+l"));
        Data.add(MapleRing.ALLATORIxDEMO("S?u2+m"));
        Data.add(MapleRing.ALLATORIxDEMO("S?u2+n"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0015y3tn"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0015y3to"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0015y3th"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0015y3ti"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0015y3tj"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0015y3tk"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0015y3td"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0015y3te"));
        Data.add(MapleRing.ALLATORIxDEMO("5y3t\u0018"));
        Data.add(MapleRing.ALLATORIxDEMO("5y3t\u000e{+"));
        Data.add(MapleRing.ALLATORIxDEMO("s?u2H=m\u0018"));
        Data.add(MapleRing.ALLATORIxDEMO("s?u2H9m=h8"));
        Data.add(MapleRing.ALLATORIxDEMO("s8"));
        Data.add(MapleRing.ALLATORIxDEMO("s;t3h9"));
        Data.add(MapleRing.ALLATORIxDEMO("5}2u.\u007f\u001fu2n5t9t("));
        Data.add(MapleRing.ALLATORIxDEMO("s;t3h9J5y7o,"));
        Data.add(MapleRing.ALLATORIxDEMO("s1r)t;h%"));
        Data.add(MapleRing.ALLATORIxDEMO("5t?"));
        Data.add(MapleRing.ALLATORIxDEMO("s2y\u001dY\u001f"));
        Data.add(MapleRing.ALLATORIxDEMO("s2y\u0018_\u0004"));
        Data.add(MapleRing.ALLATORIxDEMO("5t?_:|9y(R\fJ3n5u2"));
        Data.add(MapleRing.ALLATORIxDEMO("5t?_:|9y(W\fJ3n5u2"));
        Data.add(MapleRing.ALLATORIxDEMO("s2y\u0019L\u001d"));
        Data.add(MapleRing.ALLATORIxDEMO("s2y\u001a{(s;o9"));
        Data.add(MapleRing.ALLATORIxDEMO("s2y\u0015T\b"));
        Data.add(MapleRing.ALLATORIxDEMO("5t?P)w,"));
        Data.add(MapleRing.ALLATORIxDEMO("s2y\u0010O\u0017"));
        Data.add(MapleRing.ALLATORIxDEMO("s2y\u0011[\u0018"));
        Data.add(MapleRing.ALLATORIxDEMO("s2y\u0011{$R\f"));
        Data.add(MapleRing.ALLATORIxDEMO("s2y\u0011{$W\f"));
        Data.add(MapleRing.ALLATORIxDEMO("s2y\u0011^\u0018"));
        Data.add(MapleRing.ALLATORIxDEMO("s2y\u0011R\f"));
        Data.add(MapleRing.ALLATORIxDEMO("s2y\u0011W\f"));
        Data.add(MapleRing.ALLATORIxDEMO("s2y\f[\u0018"));
        Data.add(MapleRing.ALLATORIxDEMO("s2y\f^\u0018"));
        Data.add(MapleRing.ALLATORIxDEMO("5t?H9k\u0010\u007f*\u007f0"));
        Data.add(MapleRing.ALLATORIxDEMO("s2y\u000fj9\u007f8"));
        Data.add(MapleRing.ALLATORIxDEMO("s2y\u000fN\u000e"));
        Data.add(MapleRing.ALLATORIxDEMO("s2|3"));
        Data.add(MapleRing.ALLATORIxDEMO("5t\f{.n%"));
        Data.add(MapleRing.ALLATORIxDEMO("s2n9h=y("));
        Data.add(MapleRing.ALLATORIxDEMO("s2n9h*{0"));
        Data.add(MapleRing.ALLATORIxDEMO("s.h9v9l=t("));
        Data.add(MapleRing.ALLATORIxDEMO("5i\u001e}1U._:|9y("));
        Data.add(MapleRing.ALLATORIxDEMO("s(\u007f1"));
        Data.add(MapleRing.ALLATORIxDEMO("s(\u007f1En.o*l+o"));
        Data.add(MapleRing.ALLATORIxDEMO("s(\u007f1Y3~9"));
        Data.add(MapleRing.ALLATORIxDEMO("s(\u007f1s8"));
        Data.add(MapleRing.ALLATORIxDEMO("5n9w\u000e{2}9"));
        Data.add(MapleRing.ALLATORIxDEMO("s(\u007f1o,x%s(\u007f1"));
        Data.add(MapleRing.ALLATORIxDEMO("p)w,"));
        Data.add(MapleRing.ALLATORIxDEMO("6o1j:v%"));
        Data.add(MapleRing.ALLATORIxDEMO("Q9c\u000f\u007f(n5t;X%S(\u007f1"));
        Data.add(MapleRing.ALLATORIxDEMO("q5v0{.w)i4"));
        Data.add(MapleRing.ALLATORIxDEMO("q5i/"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0010"));
        Data.add(MapleRing.ALLATORIxDEMO("vl"));
        Data.add(MapleRing.ALLATORIxDEMO("vm"));
        Data.add(MapleRing.ALLATORIxDEMO("v=~8\u007f."));
        Data.add(MapleRing.ALLATORIxDEMO("0{8~9hn"));
        Data.add(MapleRing.ALLATORIxDEMO("v=i(I5}2o/"));
        Data.add(MapleRing.ALLATORIxDEMO("v9|("));
        Data.add(MapleRing.ALLATORIxDEMO("0\u007f*\u007f0"));
        Data.add(MapleRing.ALLATORIxDEMO("v5|9"));
        Data.add(MapleRing.ALLATORIxDEMO("0s1s(\u007f8V5|9"));
        Data.add(MapleRing.ALLATORIxDEMO("v3t9v%"));
        Data.add(MapleRing.ALLATORIxDEMO("0u2}\u000e{2}9"));
        Data.add(MapleRing.ALLATORIxDEMO("0u3i9"));
        Data.add(MapleRing.ALLATORIxDEMO("v3l9"));
        Data.add(MapleRing.ALLATORIxDEMO("0u*\u007fn"));
        Data.add(MapleRing.ALLATORIxDEMO("v("));
        Data.add(MapleRing.ALLATORIxDEMO("v*"));
        Data.add(MapleRing.ALLATORIxDEMO("0l\u0011{$"));
        Data.add(MapleRing.ALLATORIxDEMO("0l\u0011s2"));
        Data.add(MapleRing.ALLATORIxDEMO("1{8"));
        Data.add(MapleRing.ALLATORIxDEMO("1{8H=n9"));
        Data.add(MapleRing.ALLATORIxDEMO("w=}5ym"));
        Data.add(MapleRing.ALLATORIxDEMO("w=}5yn"));
        Data.add(MapleRing.ALLATORIxDEMO("w=}5yo"));
        Data.add(MapleRing.ALLATORIxDEMO("w=}5yh"));
        Data.add(MapleRing.ALLATORIxDEMO("w=}5yi"));
        Data.add(MapleRing.ALLATORIxDEMO("1{,"));
        Data.add(MapleRing.ALLATORIxDEMO("1{/n9h\u0010\u007f*\u007f0"));
        Data.add(MapleRing.ALLATORIxDEMO("1{$"));
        Data.add(MapleRing.ALLATORIxDEMO("1{$^=c/"));
        Data.add(MapleRing.ALLATORIxDEMO("1{$^5|:"));
        Data.add(MapleRing.ALLATORIxDEMO("w=b\u0019b,"));
        Data.add(MapleRing.ALLATORIxDEMO("w=b\u0010\u007f*\u007f0"));
        Data.add(MapleRing.ALLATORIxDEMO("w?N%j9"));
        Data.add(MapleRing.ALLATORIxDEMO("1~8"));
        Data.add(MapleRing.ALLATORIxDEMO("1~8H=n9"));
        Data.add(MapleRing.ALLATORIxDEMO("w9v3t;"));
        Data.add(MapleRing.ALLATORIxDEMO("w9h3t;"));
        Data.add(MapleRing.ALLATORIxDEMO("w9i3"));
        Data.add(MapleRing.ALLATORIxDEMO("w9i3o,x%s(\u007f1"));
        Data.add(MapleRing.ALLATORIxDEMO("1\u007f/i=}9"));
        Data.add(MapleRing.ALLATORIxDEMO("w9n9u."));
        Data.add(MapleRing.ALLATORIxDEMO("w4j\u0003n9w,"));
        Data.add(MapleRing.ALLATORIxDEMO("w4j\u000e"));
        Data.add(MapleRing.ALLATORIxDEMO("w4j\u000eH=n9"));
        Data.add(MapleRing.ALLATORIxDEMO("w5i?r5\u007f:"));
        Data.add(MapleRing.ALLATORIxDEMO("w1j\u0003n9w,"));
        Data.add(MapleRing.ALLATORIxDEMO("w1j\u000e"));
        Data.add(MapleRing.ALLATORIxDEMO("w1j\u000eH=n9"));
        Data.add(MapleRing.ALLATORIxDEMO("1u>"));
        Data.add(MapleRing.ALLATORIxDEMO("1u>R\f"));
        Data.add(MapleRing.ALLATORIxDEMO("w3x\u000fq5v0"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0011U\u0012 l*q*n"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0011U\u0012 l*q*j"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0011U\u0012 l*q(h"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0011U\u0012 l(q*j"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0011U\u0012 l,q+l"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0011U\u0012 l,q+n"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0011U\u0012 m*q+h"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0011U\u0012 m(q+d"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0011U\u0012 m.q+d"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0011U\u0012 m\"q(n"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0011U\u0012 m\"q(h"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0011U\u0012 n(q(h"));
        Data.add(MapleRing.ALLATORIxDEMO("1u2i(\u007f.X3u7"));
        Data.add(MapleRing.ALLATORIxDEMO("1u.j4"));
        Data.add(MapleRing.ALLATORIxDEMO("1u.j4H=t8u1"));
        Data.add(MapleRing.ALLATORIxDEMO("1u)i9U*\u007f."));
        Data.add(MapleRing.ALLATORIxDEMO("w3l9"));
        Data.add(MapleRing.ALLATORIxDEMO("1u*\u007fm"));
        Data.add(MapleRing.ALLATORIxDEMO("1u*\u007fn"));
        Data.add(MapleRing.ALLATORIxDEMO("w3l9N3"));
        Data.add(MapleRing.ALLATORIxDEMO("w,"));
        Data.add(MapleRing.ALLATORIxDEMO("1j\u000e"));
        Data.add(MapleRing.ALLATORIxDEMO("1i;"));
        Data.add(MapleRing.ALLATORIxDEMO("t=w9"));
        Data.add(MapleRing.ALLATORIxDEMO("2{1\u007f\b{;"));
        Data.add(MapleRing.ALLATORIxDEMO("2{,"));
        Data.add(MapleRing.ALLATORIxDEMO("t5t6{/n3h1"));
        Data.add(MapleRing.ALLATORIxDEMO("t3"));
        Data.add(MapleRing.ALLATORIxDEMO("2u\u001f{2y9v\u0011u)i9"));
        Data.add(MapleRing.ALLATORIxDEMO("t3\\0s,"));
        Data.add(MapleRing.ALLATORIxDEMO("t3W3l9N3V3y7\u007f."));
        Data.add(MapleRing.ALLATORIxDEMO("t3H9l5l9"));
        Data.add(MapleRing.ALLATORIxDEMO("t3h1{0"));
        Data.add(MapleRing.ALLATORIxDEMO("2u(_$n9t8"));
        Data.add(MapleRing.ALLATORIxDEMO("2u(r5t;"));
        Data.add(MapleRing.ALLATORIxDEMO("2u(I=v9"));
        Data.add(MapleRing.ALLATORIxDEMO("2j?"));
        Data.add(MapleRing.ALLATORIxDEMO("2o:|\u000fq5v0"));
        Data.add(MapleRing.ALLATORIxDEMO("\u0012o1"));
        Data.add(MapleRing.ALLATORIxDEMO("u2v%"));
        Data.add(MapleRing.ALLATORIxDEMO("u2v%J5y7o,"));
        Data.add(MapleRing.ALLATORIxDEMO("u3j/"));
        Data.add(MapleRing.ALLATORIxDEMO("u,\u007f2N.\u007f=i)h9"));
        Data.add(MapleRing.ALLATORIxDEMO("u.s;s2"));
        Data.add(MapleRing.ALLATORIxDEMO("3l9h\u000fm5t;^3o>v9"));
        Data.add(MapleRing.ALLATORIxDEMO("3l9h\u000fm5t;N.s,v9"));
        Data.add(MapleRing.ALLATORIxDEMO("j=y4s2q3"));
        Data.add(MapleRing.ALLATORIxDEMO(",{8"));
        Data.add(MapleRing.ALLATORIxDEMO(",{8H=n9"));
        Data.add(MapleRing.ALLATORIxDEMO("j=h=v%`9"));
        Data.add(MapleRing.ALLATORIxDEMO(",{.n%"));
        Data.add(MapleRing.ALLATORIxDEMO("j=h(c\u0019b,U2"));
        Data.add(MapleRing.ALLATORIxDEMO("j=n4"));
        Data.add(MapleRing.ALLATORIxDEMO(",~8"));
        Data.add(MapleRing.ALLATORIxDEMO(",~8H=n9"));
        Data.add(MapleRing.ALLATORIxDEMO("j9h:o1\u007f\ti9"));
        Data.add(MapleRing.ALLATORIxDEMO("j9h5u8"));
        Data.add(MapleRing.ALLATORIxDEMO(",r=t(u1"));
        Data.add(MapleRing.ALLATORIxDEMO(",s?q)j\u001dv0"));
        Data.add(MapleRing.ALLATORIxDEMO(",s?q\tj\u001ev3y7"));
        Data.add(MapleRing.ALLATORIxDEMO("j5y7o,S(\u007f1"));
        Data.add(MapleRing.ALLATORIxDEMO("j5~8v9"));
        Data.add(MapleRing.ALLATORIxDEMO("j0{%"));
        Data.add(MapleRing.ALLATORIxDEMO("j0u("));
        Data.add(MapleRing.ALLATORIxDEMO("j3s/u2"));
        Data.add(MapleRing.ALLATORIxDEMO(",u0\u007f\u001dh1\\5t5i4"));
        Data.add(MapleRing.ALLATORIxDEMO(",u0\u007f\u001dh1J)i4"));
        Data.add(MapleRing.ALLATORIxDEMO("j3v9[.w\u000fw=i4"));
        Data.add(MapleRing.ALLATORIxDEMO(",u0\u007f\u001dh1N3i/"));
        Data.add(MapleRing.ALLATORIxDEMO("j3u,"));
        Data.add(MapleRing.ALLATORIxDEMO("j3u."));
        Data.add(MapleRing.ALLATORIxDEMO(",u/"));
        Data.add(MapleRing.ALLATORIxDEMO("j-o9i("));
        Data.add(MapleRing.ALLATORIxDEMO(",h9i/\u007f8"));
        Data.add(MapleRing.ALLATORIxDEMO(",h9l9t(i0s,"));
        Data.add(MapleRing.ALLATORIxDEMO(",h5y9"));
        Data.add(MapleRing.ALLATORIxDEMO("j.u>"));
        Data.add(MapleRing.ALLATORIxDEMO(",h3t9"));
        Data.add(MapleRing.ALLATORIxDEMO("j.u2\u007fn"));
        Data.add(MapleRing.ALLATORIxDEMO(",h3t9I({>"));
        Data.add(MapleRing.ALLATORIxDEMO("j.u,"));
        Data.add(MapleRing.ALLATORIxDEMO(",h3n9y(N5w9"));
        Data.add(MapleRing.ALLATORIxDEMO(",h3o8"));
        Data.add(MapleRing.ALLATORIxDEMO("j)v5t;"));
        Data.add(MapleRing.ALLATORIxDEMO("--n(nE\u000fn=h("));
        Data.add(MapleRing.ALLATORIxDEMO("-o9i("));
        Data.add(MapleRing.ALLATORIxDEMO("-o9i(S8"));
        Data.add(MapleRing.ALLATORIxDEMO("k)\u007f/n5u2"));
        Data.add(MapleRing.ALLATORIxDEMO("h=t8[?n5u2"));
        Data.add(MapleRing.ALLATORIxDEMO("h=t8u1"));
        Data.add(MapleRing.ALLATORIxDEMO("h=t8U,n5u2"));
        Data.add(MapleRing.ALLATORIxDEMO("h=t8i({("));
        Data.add(MapleRing.ALLATORIxDEMO("h=t8I({("));
        Data.add(MapleRing.ALLATORIxDEMO(".{,s8|5h9"));
        Data.add(MapleRing.ALLATORIxDEMO("h=n9"));
        Data.add(MapleRing.ALLATORIxDEMO("h>"));
        Data.add(MapleRing.ALLATORIxDEMO("h9y=v0"));
        Data.add(MapleRing.ALLATORIxDEMO(".\u007f?u*\u007f."));
        Data.add(MapleRing.ALLATORIxDEMO("h9y3l9h%"));
        Data.add(MapleRing.ALLATORIxDEMO("h9y3l9h%R\f"));
        Data.add(MapleRing.ALLATORIxDEMO("h9y3l9h%W\f"));
        Data.add(MapleRing.ALLATORIxDEMO("h9y3l9h%H=n9"));
        Data.add(MapleRing.ALLATORIxDEMO("h9w3l9n4u.t/"));
        Data.add(MapleRing.ALLATORIxDEMO("h9j9{("));
        Data.add(MapleRing.ALLATORIxDEMO("h9j9{(_:|9y("));
        Data.add(MapleRing.ALLATORIxDEMO("h9j9{(I({.n\u0015t8\u007f$"));
        Data.add(MapleRing.ALLATORIxDEMO(".\u007f,v=y9"));
        Data.add(MapleRing.ALLATORIxDEMO(".\u007f-"));
        Data.add(MapleRing.ALLATORIxDEMO("h9k\u0010\u007f*\u007f0"));
        Data.add(MapleRing.ALLATORIxDEMO(".\u007f-I7s0v\u0010\u007f*\u007f0"));
        Data.add(MapleRing.ALLATORIxDEMO(".\u007f/j9y(\\\u000f"));
        Data.add(MapleRing.ALLATORIxDEMO("h9i,\u007f?n\u0011s1w)t9"));
        Data.add(MapleRing.ALLATORIxDEMO("h9i,\u007f?n\fs1w)t9"));
        Data.add(MapleRing.ALLATORIxDEMO(".\u007f/nl"));
        Data.add(MapleRing.ALLATORIxDEMO("h9i)h.\u007f?n5u2"));
        Data.add(MapleRing.ALLATORIxDEMO(".\u007f(o.t\u0011{,K\u000e"));
        Data.add(MapleRing.ALLATORIxDEMO("h9m=h8"));
        Data.add(MapleRing.ALLATORIxDEMO(".s;r("));
        Data.add(MapleRing.ALLATORIxDEMO("h5i9"));
        Data.add(MapleRing.ALLATORIxDEMO("h3j9"));
        Data.add(MapleRing.ALLATORIxDEMO(".u,\u007fn"));
        Data.add(MapleRing.ALLATORIxDEMO(".o2U2J5y7o,"));
        Data.add(MapleRing.ALLATORIxDEMO("h)i4"));
        Data.add(MapleRing.ALLATORIxDEMO(".o/rn"));
        Data.add(MapleRing.ALLATORIxDEMO("/"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000f"));
        Data.add(MapleRing.ALLATORIxDEMO("im"));
        Data.add(MapleRing.ALLATORIxDEMO("in"));
        Data.add(MapleRing.ALLATORIxDEMO("io"));
        Data.add(MapleRing.ALLATORIxDEMO("ih"));
        Data.add(MapleRing.ALLATORIxDEMO("/{8"));
        Data.add(MapleRing.ALLATORIxDEMO("i=~8v9H9{."));
        Data.add(MapleRing.ALLATORIxDEMO("i=w,v9"));
        Data.add(MapleRing.ALLATORIxDEMO("/{2y(o=h%"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000f[\b l*q*n"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000f[\b l*q*j"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000f[\b l*q(h"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000f[\b l(q*j"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000f[\b l,q+l"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000f[\b l,q+n"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000f[\b m*q+h"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000f[\b m(q+d"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000f[\b m.q+d"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000f[\b m\"q(n"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000f[\b m\"q(h"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000f[\b n(q(h"));
        Data.add(MapleRing.ALLATORIxDEMO("i=l=}9"));
        Data.add(MapleRing.ALLATORIxDEMO("/{%"));
        Data.add(MapleRing.ALLATORIxDEMO("i?{2N.{8\u007f\u001ev3y7"));
        Data.add(MapleRing.ALLATORIxDEMO("/y.{(y4"));
        Data.add(MapleRing.ALLATORIxDEMO("/y.\u007f+"));
        Data.add(MapleRing.ALLATORIxDEMO("i?h5j("));
        Data.add(MapleRing.ALLATORIxDEMO("i9{0"));
        Data.add(MapleRing.ALLATORIxDEMO("i9I5}2o/"));
        Data.add(MapleRing.ALLATORIxDEMO("/r3y7"));
        Data.add(MapleRing.ALLATORIxDEMO("/r3y7m=l9"));
        Data.add(MapleRing.ALLATORIxDEMO("i4u3nm"));
        Data.add(MapleRing.ALLATORIxDEMO("i4u3nn"));
        Data.add(MapleRing.ALLATORIxDEMO("i4u3nj"));
        Data.add(MapleRing.ALLATORIxDEMO("i4u3n\u001a"));
        Data.add(MapleRing.ALLATORIxDEMO("i4u,"));
        Data.add(MapleRing.ALLATORIxDEMO("i4u("));
        Data.add(MapleRing.ALLATORIxDEMO("i4u+~3m2"));
        Data.add(MapleRing.ALLATORIxDEMO("/r3m\u0011\u007f/i=}9"));
        Data.add(MapleRing.ALLATORIxDEMO("i5}4"));
        Data.add(MapleRing.ALLATORIxDEMO("/s;t>u=h8"));
        Data.add(MapleRing.ALLATORIxDEMO("i5}2o/"));
        Data.add("sit");
        Data.add(MapleRing.ALLATORIxDEMO("/q5v0"));
        Data.add(MapleRing.ALLATORIxDEMO("i7s2"));
        Data.add(MapleRing.ALLATORIxDEMO("/v=t;"));
        Data.add(MapleRing.ALLATORIxDEMO("/v9\u007f,"));
        Data.add(MapleRing.ALLATORIxDEMO("/v3n\u0015t8\u007f$"));
        Data.add(MapleRing.ALLATORIxDEMO("/v3n\u0011{$"));
        Data.add(MapleRing.ALLATORIxDEMO("i\u0011{,"));
        Data.add(MapleRing.ALLATORIxDEMO("/w5v9"));
        Data.add(MapleRing.ALLATORIxDEMO("i1u7\u007f/r9v0"));
        Data.add(MapleRing.ALLATORIxDEMO("i2{(y4"));
        Data.add(MapleRing.ALLATORIxDEMO("/t9\u007f."));
        Data.add(MapleRing.ALLATORIxDEMO("\u000ft3m1{2:\f{?q=}9"));
        Data.add(MapleRing.ALLATORIxDEMO("i3v8S2|3h1"));
        Data.add(MapleRing.ALLATORIxDEMO("i3o0~.s*\u007f."));
        Data.add(MapleRing.ALLATORIxDEMO("i,\u007f?"));
        Data.add(MapleRing.ALLATORIxDEMO("i,\u007f?_$"));
        Data.add(MapleRing.ALLATORIxDEMO("i,\u007f?n.o1"));
        Data.add(MapleRing.ALLATORIxDEMO("/j9\u007f8"));
        Data.add(MapleRing.ALLATORIxDEMO("/j9\u007f8H=n9"));
        Data.add(MapleRing.ALLATORIxDEMO("i({>Um"));
        Data.add(MapleRing.ALLATORIxDEMO("i({>Un"));
        Data.add(MapleRing.ALLATORIxDEMO("i({>U\u001a"));
        Data.add(MapleRing.ALLATORIxDEMO("i({>Nm"));
        Data.add(MapleRing.ALLATORIxDEMO("i({>Nn"));
        Data.add(MapleRing.ALLATORIxDEMO("i({>N\u001a"));
        Data.add(MapleRing.ALLATORIxDEMO("/n=t8"));
        Data.add(MapleRing.ALLATORIxDEMO("i({2~l"));
        Data.add("stand1");
        Data.add(MapleRing.ALLATORIxDEMO("i({2~n"));
        Data.add(MapleRing.ALLATORIxDEMO("i({2~o"));
        Data.add(MapleRing.ALLATORIxDEMO("i({2~h"));
        Data.add(MapleRing.ALLATORIxDEMO("i({2~i"));
        Data.add(MapleRing.ALLATORIxDEMO("i({2~j"));
        Data.add(MapleRing.ALLATORIxDEMO("/n=h("));
        Data.add(MapleRing.ALLATORIxDEMO("/n=n9Y4{2}9S(\u007f1"));
        Data.add(MapleRing.ALLATORIxDEMO("i(u.w>h9{7"));
        Data.add(MapleRing.ALLATORIxDEMO("i(h=s;r("));
        Data.add(MapleRing.ALLATORIxDEMO("/n.\u007f(y4"));
        Data.add(MapleRing.ALLATORIxDEMO("/n)t2\u007f8"));
        Data.add(MapleRing.ALLATORIxDEMO("/o?y9i/"));
        Data.add(MapleRing.ALLATORIxDEMO("i)v7"));
        Data.add(MapleRing.ALLATORIxDEMO("i)w1u2_*\u007f2n\u0012j?"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000fO\u0012 l*q*n"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000fO\u0012 l*q*j"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000fO\u0012 l*q(h"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000fO\u0012 l(q*j"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000fO\u0012 l,q+l"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000fO\u0012 l,q+n"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000fO\u0012 m*q+h"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000fO\u0012 m(q+d"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000fO\u0012 m.q+d"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000fO\u0012 m\"q(n"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000fO\u0012 m\"q(h"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000fO\u0012 n(q(h"));
        Data.add(MapleRing.ALLATORIxDEMO("i)h,h5i9"));
        Data.add(MapleRing.ALLATORIxDEMO("i+\u007f9j\u001au.^.u,"));
        Data.add(MapleRing.ALLATORIxDEMO("/m5t;Um"));
        Data.add(MapleRing.ALLATORIxDEMO("/m5t;Un"));
        Data.add(MapleRing.ALLATORIxDEMO("/m5t;Uo"));
        Data.add(MapleRing.ALLATORIxDEMO("/m5t;U\u001a"));
        Data.add(MapleRing.ALLATORIxDEMO("/m5t;Jm"));
        Data.add(MapleRing.ALLATORIxDEMO("i+s2}\f+\fu0\u007f\u001dh1"));
        Data.add(MapleRing.ALLATORIxDEMO("/m5t;Jn"));
        Data.add(MapleRing.ALLATORIxDEMO("i+s2}\f(\fu0\u007f\u001dh1"));
        Data.add(MapleRing.ALLATORIxDEMO("/m5t;J\u001a"));
        Data.add(MapleRing.ALLATORIxDEMO("/m5t;Nm"));
        Data.add(MapleRing.ALLATORIxDEMO("/m5t;Nn"));
        Data.add(MapleRing.ALLATORIxDEMO("i+s2}\b(\fu0\u007f\u001dh1"));
        Data.add(MapleRing.ALLATORIxDEMO("/m5t;No"));
        Data.add(MapleRing.ALLATORIxDEMO("/m5t;N\u001a"));
        Data.add(MapleRing.ALLATORIxDEMO("("));
        Data.add(MapleRing.ALLATORIxDEMO("({1s2}\u0011u>"));
        Data.add(MapleRing.ALLATORIxDEMO("n=h;\u007f("));
        Data.add(MapleRing.ALLATORIxDEMO("\b{.}9n\u001as9v8S\u0018"));
        Data.add(MapleRing.ALLATORIxDEMO("(\u007f8s3o/"));
        Data.add(MapleRing.ALLATORIxDEMO("N9i(S\u0018"));
        Data.add(MapleRing.ALLATORIxDEMO("n9b("));
        Data.add(MapleRing.ALLATORIxDEMO("n4{2q/}5l5t;"));
        Data.add(MapleRing.ALLATORIxDEMO("n4{+"));
        Data.add(MapleRing.ALLATORIxDEMO("\bR\t l*q*n"));
        Data.add(MapleRing.ALLATORIxDEMO("\bR\t l*q*j"));
        Data.add(MapleRing.ALLATORIxDEMO("\bR\t l*q(h"));
        Data.add(MapleRing.ALLATORIxDEMO("\bR\t l(q*j"));
        Data.add(MapleRing.ALLATORIxDEMO("\bR\t l,q+l"));
        Data.add(MapleRing.ALLATORIxDEMO("\bR\t l,q+n"));
        Data.add(MapleRing.ALLATORIxDEMO("\bR\t m*q+h"));
        Data.add(MapleRing.ALLATORIxDEMO("\bR\t m(q+d"));
        Data.add(MapleRing.ALLATORIxDEMO("\bR\t m.q+d"));
        Data.add(MapleRing.ALLATORIxDEMO("\bR\t m\"q(n"));
        Data.add(MapleRing.ALLATORIxDEMO("\bR\t m\"q(h"));
        Data.add(MapleRing.ALLATORIxDEMO("\bR\t n(q(h"));
        Data.add(MapleRing.ALLATORIxDEMO("n5y7\u007f(S(\u007f1S\u0018"));
        Data.add(MapleRing.ALLATORIxDEMO("(s?q9n\u0015n9w\ti9"));
        Data.add(MapleRing.ALLATORIxDEMO("n5v9"));
        Data.add(MapleRing.ALLATORIxDEMO("n5w9"));
        Data.add(MapleRing.ALLATORIxDEMO("n5w9v9{,"));
        Data.add(MapleRing.ALLATORIxDEMO("(s1\u007f\u0010s1s(\u007f8"));
        Data.add(MapleRing.ALLATORIxDEMO("(u,"));
        Data.add(MapleRing.ALLATORIxDEMO("(u.j9~3"));
        Data.add(MapleRing.ALLATORIxDEMO("(h=~\u001ev3y7"));
        Data.add(MapleRing.ALLATORIxDEMO("n.{8\u007f\u001dl=s0{>v9"));
        Data.add(MapleRing.ALLATORIxDEMO("n.{8\u007f\u001ev3y7"));
        Data.add(MapleRing.ALLATORIxDEMO("n.{8\u007f>v3y7"));
        Data.add(MapleRing.ALLATORIxDEMO("(h=}9n\u001ev3y7"));
        Data.add(MapleRing.ALLATORIxDEMO("(h=t/|3h1"));
        Data.add(MapleRing.ALLATORIxDEMO("n.{2i:u.w=n5u2"));
        Data.add(MapleRing.ALLATORIxDEMO("n.s,v9|5h9"));
        Data.add(MapleRing.ALLATORIxDEMO("\bO\u0019 l*q*n"));
        Data.add(MapleRing.ALLATORIxDEMO("\bO\u0019 l*q*j"));
        Data.add(MapleRing.ALLATORIxDEMO("\bO\u0019 l*q(h"));
        Data.add(MapleRing.ALLATORIxDEMO("\bO\u0019 l(q*j"));
        Data.add(MapleRing.ALLATORIxDEMO("\bO\u0019 l,q+l"));
        Data.add(MapleRing.ALLATORIxDEMO("\bO\u0019 l,q+n"));
        Data.add(MapleRing.ALLATORIxDEMO("\bO\u0019 m*q+h"));
        Data.add(MapleRing.ALLATORIxDEMO("\bO\u0019 m(q+d"));
        Data.add(MapleRing.ALLATORIxDEMO("\bO\u0019 m.q+d"));
        Data.add(MapleRing.ALLATORIxDEMO("\bO\u0019 m\"q(n"));
        Data.add(MapleRing.ALLATORIxDEMO("\bO\u0019 m\"q(h"));
        Data.add(MapleRing.ALLATORIxDEMO("\bO\u0019 n(q(h"));
        Data.add(MapleRing.ALLATORIxDEMO("n)h2"));
        Data.add(MapleRing.ALLATORIxDEMO("(m5t7v5t;"));
        Data.add(MapleRing.ALLATORIxDEMO("n%j9"));
        Data.add(MapleRing.ALLATORIxDEMO("o5"));
        Data.add(MapleRing.ALLATORIxDEMO("o5^=n="));
        Data.add(MapleRing.ALLATORIxDEMO("o2|=l3h5n9S(\u007f1"));
        Data.add(MapleRing.ALLATORIxDEMO(")t5n\fh5y9"));
        Data.add(MapleRing.ALLATORIxDEMO(")j/\u007f("));
        Data.add(MapleRing.ALLATORIxDEMO("o/\u007f\u0018\u007f0{%"));
        Data.add(MapleRing.ALLATORIxDEMO("*{1j5h9"));
        Data.add(MapleRing.ALLATORIxDEMO("l=t5i4_*\u007f2n\u0012j?"));
        Data.add(MapleRing.ALLATORIxDEMO("*u1s("));
        Data.add(MapleRing.ALLATORIxDEMO("+"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000b"));
        Data.add(MapleRing.ALLATORIxDEMO("m=s("));
        Data.add(MapleRing.ALLATORIxDEMO("+{0qm"));
        Data.add(MapleRing.ALLATORIxDEMO("+{0qn"));
        Data.add(MapleRing.ALLATORIxDEMO("+{.w/o,j3h("));
        Data.add(MapleRing.ALLATORIxDEMO("m=h2"));
        Data.add(MapleRing.ALLATORIxDEMO("m=l9"));
        Data.add(MapleRing.ALLATORIxDEMO("m9{7t9i/"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000b_\u0018 l*q*n"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000b_\u0018 l*q*j"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000b_\u0018 l*q(h"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000b_\u0018 l(q*j"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000b_\u0018 l,q+l"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000b_\u0018 l,q+n"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000b_\u0018 m*q+h"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000b_\u0018 m(q+d"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000b_\u0018 m.q+d"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000b_\u0018 m\"q(n"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000b_\u0018 m\"q(h"));
        Data.add(MapleRing.ALLATORIxDEMO("\u000b_\u0018 n(q(h"));
        Data.add(MapleRing.ALLATORIxDEMO("m4{("));
        Data.add(MapleRing.ALLATORIxDEMO("+r5h0m5t8"));
        Data.add(MapleRing.ALLATORIxDEMO("m5t8i4u("));
        Data.add(MapleRing.ALLATORIxDEMO("m5t7"));
        Data.add(MapleRing.ALLATORIxDEMO("m3h0~\u0011i;"));
        Data.add(MapleRing.ALLATORIxDEMO("%\u007f/"));
        Data.add(MapleRing.ALLATORIxDEMO("&"));
        Data.add(MapleRing.ALLATORIxDEMO("`5}&{;"));
    }

    public static /* synthetic */ boolean NeedToRemove(String a2) {
        int n2;
        boolean bl = true;
        if (Data.contains(a2)) {
            bl = false;
            return false;
        }
        String[] arrstring = keepString;
        int n3 = keepString.length;
        int n4 = n2 = 0;
        while (n4 < n3) {
            String string = arrstring[n2];
            if (a2.contains(string)) {
                bl = false;
                return false;
            }
            n4 = ++n2;
        }
        return bl;
    }

    public /* synthetic */ ItemData() {
        ItemData a2;
    }
}

