/*
 * Decompiled with CFR 0.150.
 */
package tools.use.xml.cleaner;

import client.MapleCoolDownValueHolder;
import client.messages.ConsoleCommandObject;
import java.util.ArrayList;
import java.util.List;

public class MobData {
    public static final /* synthetic */ List<String> Data;
    public static /* synthetic */ String[] keepString;

    private static /* synthetic */ void ALLATORIxDEMO() {
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("}\n"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO(":\u0012"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("[\u007fY"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO(":@/J4M"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("[n_}ysOrN"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("B)F:t:Q5J5D"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("}Nh[\u007fR"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO(":W/B8K=B8J5D"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("[hN}Yw\u000b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("B/W:@0\u0011"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("[hN}Yw\t"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("B/W:@0\u0017"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("[hN}Yw\u000f"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("B/W:@0\u0015"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("[hN}Yw{zNyH"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("B/W:@0`4V5W"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("~[pV"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("A:M"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("~[rw}J"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("9B5n(D"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("X}THCl_"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("9L?Z\u001aW/B8H"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("~UxC}Nh[\u007fQ"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("9L(P"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("~Oz\\"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("A.O7F/p+F>G"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("Yt[o_"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("8K:P>p+F>G"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("\u007fR}N}x}VpUsT"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("@3B/a:O7L4M"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("YsWQj"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("@4M"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("YsTQj"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("8L4O\u001fB6B<F"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("\u007fUsVX[q[{_LHsX"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("@4V5W"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("x[q[{_xxewsX"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("?F:G7Z\u001aW/B8H"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("^y[pC"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("G>E:V7W"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("^y\\}OpNTj"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("G>E:V7W\u0016s"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("^yV}C"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("G>O\"B"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("^yIy[o_"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("G2F"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("xSy\u000b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("?J>\u0011"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("xSy|"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("G2P:A7F"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("^uIy[o_"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("G4e2Q(W"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("^stsNN_qUj_"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("?Q4S\u0012W>N\u000bF)J4G"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("xOn[hSsT"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO(">E=F8W"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("_z\\yYh\n"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("F=E>@/b=W>Q"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("y\\z_\u007fNXSoN}T\u007f_"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO(">E=F8W2U>p0J7O"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("y\\z_\u007fNHCl_"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO(">O>N\u001aW/Q"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("_j["));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("F#S"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("_dJpUoSj_N_k[n^"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("e"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("Z\u000bT\bP\bO\bU\u000b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u001d\u0012\u0017\u0012"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("Z\u000bP\u000bU\u000bO\u000bT\u000b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u001d\u0012\u0017\u0012\u0012\u0012\b\u0012\u0013\u0012\u000b\u0012"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("Z\b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u001d\u0011\u0013\u0010"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("Z\bU\b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u001d\u0011\u0012\u0011\u0013\u0010"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("Z\bU\bP\bO\b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u001d\u0011\u0012\u0011\b\u0012\u0013\u0011"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("Z\bU\bO\bT\bP\b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u001d\u0011\u0012\u0010"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("Z\bU\tO\u000b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u001d\u0011\u0017\u0011"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("Z\bP\bU\bO\u000bT\b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u001d\u0011\u0017\u0011\u0012\u0011\b\u0011\u0013\u0011\u000b\u0011"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("Z\bP\t"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u001d\u0011\u0017\u0010\u0013\u0010\u0012\u0010\b\u0012"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("Z\bP\tU\tO\u000b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u001d\u0011\b\u0011\u0013\u0010"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("Z\bO\t"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u001d\u0010"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("Z\tT\t"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u001d\u0010\u0013\u0010\u0012\u0010"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("Z\tU\u000bP\u000bO\u000bT\u000bL\u000b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u001d\u0010\u0012\u0011"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("Z\tU\t"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u001d\u0010\u0017\u0011\u001d\u0011"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("Z\tP\bU\bO\u000b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u001d\u0010\u0017\u0010"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("Z\tP\tU\tO\tT\tL\t"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u001d\u0010\u000b\u0011"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("Z\tO\u000b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u001d\u0010\b\u0011"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("Z\tO\t"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("=B7O"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("\\u_p^"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("E2Q(W\u001aW/B8H"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("\\uHoN}Nh[\u007fQ"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("E2P3J5D\u0010J5D\u0016L9p8L)F"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("\\uBX[q[{_"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("=J#F?`6G"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("\\uBy^X[q[{_"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("E7Z"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("zVeil_y^"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("=O\"P+F>G"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("ZVeil_y^"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("=P"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("]yN_j"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u0013\u0012\u001d\u0011\u0017\u0011\u0012\u0011"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("T\b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u0013\u0011\u001d\u0010"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("T\bU\t"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u0013\u0011\u0017\u0011\u0012\u0010"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("T\bO\b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u0013\u0010"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("T\tZ\t"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u0013\u0010\u001d\u0010\u0012\u0012"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("T\tZ\tU\t"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u0013\u0010\u0012\u0011"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("T\tU\bZ\t"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u0013\u0010\u0012\u0011\u0017\u0011"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("T\tU\bO\u000b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u0013\u0010\u0012\u0010"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("T\tP\bO\u000bZ\b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u0013\u0010\u0017\u0010"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("T\tO\u000b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u0013\u0010\b\u0011"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("t_}^"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("3J?F\u0013s"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("tSx_R[q_"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("3J?F5B6F"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("RuN"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("3J/\u0012"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("tSh{zNyH"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("3S"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("rL]}O{_TSx_"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("3S\tF8L-F)Z"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("tJH[{x{YsVsH"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("3S\u000fB<`4O4Q"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("s"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u0012\u0012\u0017\u0011\u001d\u0010"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("U\bZ\b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u0012\u0011\u001d\u0011\u0017\u0011"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("U\bZ\bP\bT\b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u0012\u0011\u001d\u0011\u0017\u0011\u0013\u0011\b\u0011"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("U\bZ\bP\bO\b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u0012\u0011\u001d\u0011\u0017\u0011\b\u0011\u0013\u0011"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("U\bZ\t"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u0012\u0011\u001d\u0010\u0017\u0010"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("U\bP\bZ\bT\b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u0012\u0011\u0017\u0011\u001d\u0010"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("U\bP\t"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u0012\u0011\b\u0012\u0013\u0011"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("U\bO\t"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u0012\u0010"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("U\tZ\u000bP\u000bO\u000bT\u000bL\u000b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u0012\u0010\u001d\u0011"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("U\tP\b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u0012\u0010\b\u0011\u001d\u0011"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("U\tO\t"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u0012\u0010\b\u0010\u0013\u0012"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("u^"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("2D5L)F\u001dJ>O?l.W"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("S{TsHyiwSpV"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("2Mk\u0011"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("sr^yB"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("2M=L"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("uTh_nL}V"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("2M-J5@2A7F"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("vOqJ"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("1V6S\u001aW/B8H"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("wTy_"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("H5L8H9B8H"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("v"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u0017\u0011"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("P\bZ\b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u0017\u0011\u0013\u0011\b\u0011\u0012\u0012\u001d\u0010"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("P\bU\u000bT\t"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u0017\u0011\u0012\u0011\u001d\u0010"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("P\bU\bT\t"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u0017\u0011\u0012\u0010"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("P\bO\b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u0017\u0011\b\u0010"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("P\t"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u0017\u0010\u001d\u0011"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("P\tZ\t"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u0017\u0010\u0013\u0010"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("P\tU\b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u0017\u0010\b\u0010"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("P\tO\tZ\b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("O>U>O"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("pSrQ"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("7L(F\u0012W>N"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("pN"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u0016b\u001fB6B<F"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("W}]uY"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("N:[\u0013s"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("W}BQj"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("N9L4H\u0012g"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("Q~X[q[{_"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("6J(P"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("WsXHCl_"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("6L-F"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("qJ^OnT"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("6S9V)M"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("qJN_\u007fUj_nC"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("5L\u001dO2S"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("TsHy]yT"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("M4W\u001aW/B8H"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("sTpCRUnW}V]Nh[\u007fQ"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("4Q2D2M"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("UiN,\n"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u000b\u0011\u0013\u0011\u001d\u0011\u0012\u0011"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("L\bP\tZ\t"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u000b\u0010\u001d\u0011"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("L{X[q[{_"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\u000bg\u001fB6B<F"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("JyN"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("+L)W:O"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("JsI"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("S4W:O"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("lHsX"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("+Q4S"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("lO~VuYN_k[n^"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("+V(K>G"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("Ki_oN"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("R.F(W\u0012g"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("H"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("Q:M?L6s4P"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("H}T{_"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("Q:Q>j/F6g)L+o>U>O"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("nX"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO(")F8W"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("Hy]yT"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("Q>N4U>b=W>Q"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("n_qUj_STQSoI"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("Q>N4U>r.F(W"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("n_jSj_"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO(")L/B/F\u000bF)J4G"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("i"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\b\u0012"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("O\u000bZ\bP\b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\b\u0012\u0013\u0012"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("O\u000bT\u000bZ\u000bU\u000b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\b\u0012\u0013\u0012\u001d\u0010\u0017\u0010"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("O\u000bT\b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\b\u0012\u0013\u0010"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("O\u000bP\tT\u000b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\b\u0011"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("O\bZ\u000bU\t"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\b\u0011\u001d\u0011"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("O\bZ\t"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\b\u0011\u0012\u0010\u001d\u0010"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("O\bP\b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\b\u0011\u0017\u0010"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("O\t"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("\b\u0010\u001d\u0011"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("O\tZ\t"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("P>O=g>P/Q.@/J4M"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("IwSpV"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("(H2O7\u0012"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("IwSpV-\f"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("(H2O7\u0011"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("oQuVp\t"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("(H2O7\u0017"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("oQuVp\u000f"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("(H2O7\u0015"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("oQuVp\r"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("(H2O7\u001b"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("oJ"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("P+F:H"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("Il_y^"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("p+F>G"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("oN,\n"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("P/B5G"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("Ih[nN"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("P/B/F"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("oNsJ"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("(V6N4M\u000fZ+F"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("NsJ,\n"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("W)F6A7F"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("hCl_"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO(".M?F:G"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("B"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("Z"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("@"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("!\u0013"));
        Data.add(ConsoleCommandObject.ALLATORIxDEMO("f\u000b"));
        Data.add(MapleCoolDownValueHolder.ALLATORIxDEMO("!J<Y:D"));
    }

    public static /* synthetic */ boolean NeedToRemove(String a2) {
        int n2;
        boolean bl = true;
        if (Data.contains(a2)) {
            bl = false;
            return false;
        }
        String[] arrstring = keepString;
        int n3 = keepString.length;
        int n4 = n2 = 0;
        while (n4 < n3) {
            String string = arrstring[n2];
            if (a2.contains(string)) {
                bl = false;
                return false;
            }
            n4 = ++n2;
        }
        return bl;
    }

    public static /* synthetic */ {
        Data = new ArrayList<String>();
        String[] arrstring = new String[6];
        arrstring[0] = ConsoleCommandObject.ALLATORIxDEMO("IwSpV");
        arrstring[1] = MapleCoolDownValueHolder.ALLATORIxDEMO(":W/B8H");
        arrstring[2] = "bobo";
        arrstring[3] = ConsoleCommandObject.ALLATORIxDEMO("et[oR");
        arrstring[4] = MapleCoolDownValueHolder.ALLATORIxDEMO("u\r");
        arrstring[5] = "/";
        keepString = arrstring;
        MobData.ALLATORIxDEMO();
    }

    public /* synthetic */ MobData() {
        MobData a2;
    }
}

