/*
 * Decompiled with CFR 0.150.
 */
package FuckingHackerToby;

import FuckingHackerToby.Rb;
import FuckingHackerToby.Ua;
import java.awt.image.BufferedImage;
import java.util.Arrays;
import java.util.List;
import tools.ArrayMap;

public final class e {
    public static final /* synthetic */ BufferedImage N;
    public static final /* synthetic */ BufferedImage A;
    public static final /* synthetic */ BufferedImage F;
    public static final /* synthetic */ BufferedImage[] u;
    public static final /* synthetic */ BufferedImage I;
    public static final /* synthetic */ BufferedImage G;
    public static final /* synthetic */ BufferedImage C;
    public static final /* synthetic */ BufferedImage c;
    public static final /* synthetic */ BufferedImage[] d;
    public static final /* synthetic */ BufferedImage h;
    public static final /* synthetic */ BufferedImage t;
    public static final /* synthetic */ BufferedImage P;
    public static final /* synthetic */ BufferedImage v;
    public static final /* synthetic */ BufferedImage B;
    public static final /* synthetic */ BufferedImage R;
    public static final /* synthetic */ BufferedImage Y;
    public static final /* synthetic */ BufferedImage V;
    public static final /* synthetic */ BufferedImage l;
    public static final /* synthetic */ BufferedImage X;
    public static final /* synthetic */ BufferedImage j;
    public static final /* synthetic */ BufferedImage i;
    public static final /* synthetic */ BufferedImage n;
    public static final /* synthetic */ BufferedImage M;
    public static final /* synthetic */ BufferedImage L;
    public static final /* synthetic */ BufferedImage[] K;
    public static final /* synthetic */ BufferedImage e;
    public static final /* synthetic */ BufferedImage[] a;
    public static final /* synthetic */ BufferedImage Q;
    public static final /* synthetic */ BufferedImage D;
    public static final /* synthetic */ BufferedImage o;
    public static final /* synthetic */ BufferedImage y;
    public static final /* synthetic */ BufferedImage J;
    public static final /* synthetic */ BufferedImage[] Ha;
    public static final /* synthetic */ BufferedImage W;
    public static final /* synthetic */ BufferedImage g;
    public static final /* synthetic */ BufferedImage x;
    public static final /* synthetic */ BufferedImage z;
    public static final /* synthetic */ Rb ca;
    public static final /* synthetic */ BufferedImage q;
    public static final /* synthetic */ BufferedImage O;
    public static final /* synthetic */ BufferedImage p;
    public static final /* synthetic */ BufferedImage S;
    public static final /* synthetic */ BufferedImage f;
    public static final /* synthetic */ BufferedImage b;
    public static final /* synthetic */ BufferedImage H;
    public static final /* synthetic */ BufferedImage T;
    public static final /* synthetic */ BufferedImage r;
    public static final /* synthetic */ BufferedImage Z;
    public static final /* synthetic */ List<BufferedImage> U;
    public static final /* synthetic */ BufferedImage m;
    public static final /* synthetic */ BufferedImage[] ALLATORIxDEMO;
    public static final /* synthetic */ BufferedImage E;
    public static final /* synthetic */ BufferedImage s;
    public static final /* synthetic */ BufferedImage k;
    public static final /* synthetic */ BufferedImage w;

    private /* synthetic */ e() {
        e a2;
    }

    public static /* synthetic */ {
        ca = new Rb(Ua.ALLATORIxDEMO(Ua.H(ArrayMap.ALLATORIxDEMO("2\ny\u001d3\u001c9\u001a$\f3@?\f9\u0001%A&\u00011")), 2.0f), 32, 32);
        Ha = ca.ALLATORIxDEMO();
        y = Ha[26];
        W = Ua.ALLATORIxDEMO(y, 32, 32);
        p = Ua.ALLATORIxDEMO(y, 64, 64);
        V = Ua.ALLATORIxDEMO(y, 128, 128);
        BufferedImage[] arrbufferedImage = new BufferedImage[4];
        arrbufferedImage[0] = y;
        arrbufferedImage[1] = W;
        arrbufferedImage[2] = p;
        arrbufferedImage[3] = V;
        u = arrbufferedImage;
        U = Arrays.asList(u);
        x = Ha[0];
        q = Ha[1];
        X = Ha[2];
        z = Ha[3];
        Y = Ha[4];
        O = Ha[5];
        s = Ha[6];
        n = Ha[7];
        v = Ha[8];
        T = Ha[9];
        R = Ha[10];
        N = Ha[11];
        S = Ha[12];
        r = Ha[13];
        Q = Ha[14];
        o = Ha[15];
        Z = Ha[16];
        t = Ha[17];
        P = Ha[18];
        w = Ha[19];
        G = Ha[20];
        b = Ha[21];
        c = Ha[22];
        l = Ha[23];
        m = Ha[24];
        A = Ha[25];
        f = Ha[26];
        h = Ha[27];
        D = Ha[28];
        L = Ha[29];
        j = Ha[30];
        i = Ha[31];
        J = Ha[32];
        M = Ha[33];
        I = Ha[34];
        F = Ha[35];
        C = Ha[36];
        H = Ha[37];
        e = Ha[38];
        E = Ha[39];
        g = Ha[40];
        B = Ha[41];
        k = Ha[42];
        BufferedImage[] arrbufferedImage2 = new BufferedImage[5];
        arrbufferedImage2[0] = q;
        arrbufferedImage2[1] = X;
        arrbufferedImage2[2] = z;
        arrbufferedImage2[3] = v;
        arrbufferedImage2[4] = b;
        K = arrbufferedImage2;
        BufferedImage[] arrbufferedImage3 = new BufferedImage[3];
        arrbufferedImage3[0] = s;
        arrbufferedImage3[1] = r;
        arrbufferedImage3[2] = o;
        a = arrbufferedImage3;
        BufferedImage[] arrbufferedImage4 = new BufferedImage[5];
        arrbufferedImage4[0] = x;
        arrbufferedImage4[1] = n;
        arrbufferedImage4[2] = S;
        arrbufferedImage4[3] = T;
        arrbufferedImage4[4] = P;
        d = arrbufferedImage4;
        BufferedImage[] arrbufferedImage5 = new BufferedImage[5];
        arrbufferedImage5[0] = w;
        arrbufferedImage5[1] = A;
        arrbufferedImage5[2] = m;
        arrbufferedImage5[3] = Q;
        arrbufferedImage5[4] = G;
        ALLATORIxDEMO = arrbufferedImage5;
    }
}

